# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20190324_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='neighborhood_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_hood', to='hood.NeighbourHood'),
        ),
    ]
