# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20190324_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='gallery/')),
                ('image_description', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
